TMF-F4 get team by uuid
JujaLabs/teams pull request #27
Opened 2017-07-19 14:02 UTC by ivshapovalov

Connect to #11
Connect to #12

2017-07-20 20:40 UTC, OlgaKulikova requested changes
Please look at my comments and answer the questions.

2017-07-20 20:40 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/dao/TeamRepository.java
> +        );
I need explanation what is going on in this agregation.

2017-07-20 20:40 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/dao/TeamRepository.java
> +    private class User {
What is it? Why you need this class? Where do you get user's name?

2017-07-20 20:40 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/entity/Team.java
> +import com.fasterxml.jackson.databind.*;
please don't use * for imports

2017-07-20 20:40 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/service/TeamService.java
> +        team.setDeactivateDate(Date.from(Instant.now()));
In other places date has such format -  Date.from(LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant());

2017-07-20 20:40 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/service/Utils.java
> +    public static String convertToString(Reader reader) throws IOException {
If you use this method only in the tests you should replace Utils class to the test folder.

2017-07-20 20:40 UTC, OlgaKulikova commented on src/test/java/ua/com/juja/microservices/acceptance/TeamsAcceptanceTest.java
> +import static ua.com.juja.microservices.teams.service.Utils.convertToString;
please use static imports only for testing libraries (it's common approach). It's difficult to understand quickly where this method from.

2017-07-20 20:40 UTC, OlgaKulikova commented on src/test/java/ua/com/juja/microservices/teams/dao/TeamRepositoryTest.java
> +        for (int i = 0; i < actual.size(); i++) {
If the Team entity has equals and hashcode overrided methods, you can check these entities with `assertEquals(expected, actual)` only

2017-07-20 20:40 UTC, OlgaKulikova commented on src/test/java/ua/com/juja/microservices/teams/dao/TeamRepositoryTest.java
> +        Date actualDate = Date.from(LocalDateTime.now().toInstant(ZoneOffset.UTC));
Why you use different approaches to set dates?

2017-07-20 20:40 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/entity/Team.java
> +    public String toJSON() {
Why we need this method?

2017-07-21 02:21 UTC, ivshapovalov commented on src/main/java/ua/com/juja/microservices/teams/dao/TeamRepository.java
> +    private class User {
This class is used for automapping of Mongo's aggregation results 
        AggregationResults<User> groupResults
                = mongoTemplate.aggregate(agg, Team.class, User.class);
        List<User> usersInActiveTeams = groupResults.getMappedResults();

2017-07-21 02:42 UTC, ivshapovalov commented on src/main/java/ua/com/juja/microservices/teams/service/TeamService.java
> +        team.setDeactivateDate(Date.from(Instant.now()));
Done

2017-07-21 02:50 UTC, ivshapovalov commented on src/test/java/ua/com/juja/microservices/teams/dao/TeamRepositoryTest.java
> +        Date actualDate = Date.from(LocalDateTime.now().toInstant(ZoneOffset.UTC));
Fixed

2017-07-21 09:02 UTC, OlgaKulikova commented on src/test/java/ua/com/juja/microservices/teams/dao/TeamRepositoryTest.java
> +        for (int i = 0; i < actual.size(); i++) {
your implementation is correct

2017-07-21 09:04 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/entity/Team.java
> +    public String toJSON() {
move it to Utils test class

2017-07-21 09:04 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/dao/TeamRepository.java
> +    private class User {
Rename to Member with field String uuid.

2017-07-21 09:05 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/teams/dao/TeamRepository.java
> +        );
Leave it as is (except renaming User to Member and name to uuid)

2017-07-21 12:20 UTC, starikivan commented on src/main/java/ua/com/juja/microservices/teams/controller/TeamController.java
> +        log.debug("Received 'Get team' request. Get team team of user {}", uuid);
Correct this - Get team team

2017-07-21 20:40 UTC, OlgaKulikova approved these changes

2017-07-21 20:40 UTC, merged